version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name last-app --s3-location s3://last111/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src